### ISSUE TITLE
getenv("RELEASE_STORE_FILE_PATH") must not be null

### ISSUE THREAD

**Issue by xyang5987** [erfansn/SiliconeCalculator#48]
After I git the code to my macbook pro and rebuild it, I got the error:

getenv("RELEASE_STORE_FILE_PATH") must not be null

Is there any configuration I missed?

Please help. Thanks.

**Comment by erfansn** [comment]
You have two options: 
- Remove the signing config of the **Release** build variant
- Set the keystore specifications as an Environment Variable.

**Comment by erfansn** [comment]
If your issue has been resolved, please close it.

**Comment by xyang5987** [comment]
Thanks
