### ISSUE TITLE
Calculator looks tiny

### ISSUE THREAD

**Issue by akrram0** [erfansn/SiliconeCalculator#50]
The calculator looks small on my Oppo a74
Resolution: 1080×2400
Android 13
![Screenshot_2024-06-19-21-42-37-58_a734be0afb66bae1418a80819b83e228.jpg](https://github.com/erfansn/SiliconeCalculator/assets/140515513/c2eb5ee0-86e3-4440-94e4-6b0ecf82ba7a)

**Comment by erfansn** [comment]
I will definitely consider it for the next update.

**Comment by erfansn** [comment]
It is fixed in the new release.
