### ISSUE TITLE
Haptic Feedback support

### ISSUE THREAD

**Issue by dontlookherepls** [erfansn/SiliconeCalculator#59]
The title speak for himself, I would love to it implemented.

**Comment by erfansn** [comment]
I had previously implemented it to vibrate when the buttons are pressed, but because of the different function of the C/AC button, I removed it and the phone vibrates only when the button is pressed for a long time.

If you have a different model in mind, please let me know.

**Comment by dontlookherepls** [comment]
For now the only thing that i could think of is the following :
- Add an AC button and a backspace by shrinking the zero and moving the ± somewhere else (Or even removing it ?)

But I think that this goes against your vision of the project.

**Comment by erfansn** [comment]
Unfortunately, I can't do this because it is messed up. Anyway, if you have any other suggestion, please let me know.

**Comment by dontlookherepls** [comment]
For curiosity, why this can't work ?
> I had previously implemented it to vibrate when the buttons are pressed, but because of the different function of the C/AC button, I removed it and the phone vibrates only when the button is pressed for a long time.

I don't know how to put in words but why can't you have a feedback after you press the button once (C) and also having another feedback if you long press it (AC)  ? I hope this is understandable.

**Comment by erfansn** [comment]
Because the AC action is considered an implicit action for the C button, as a result, it should be notified to the user with a special effect.

**Comment by erfansn** [comment]
Please close this issue if you got your answer

**Comment by dontlookherepls** [comment]
> Why, can you now receive feedback in the form of vibration when you do a long touch on the C button, it's just as if the vibrate feature should be activated in some phones.

Still not understanding.

**Comment by erfansn** [comment]
In the first version of the calculator, because there is no dual function for any button, as a result, Haptic Feedback was applied to all buttons, but when I replaced the C button in the new version with the AC button, I decided that when the C button is touched for a long time  Let the AC function be implemented and in order to make this issue tangible for the user, I have used Haptic Feedback only this time. I hope I have answered your question.
